Repository Seagate/cortx, pull requests merged in 2021-02, with the labels that each got.

#670 Adding mariyappanp in cortx contributors.md
  CONTRIBUTORS.md
Labels: cla-signed

#677 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#676 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#681 PR Template
  .github/pull_request_template.md
Labels: assigned_jira, cla-signed

#660 Signed-off-by: Mayur Gupta <Mayur.Gupta@Seagate.com>
  Community_Roadmap.md
Labels: cla-signed

#668 Update README.rst
  doc/meetings/README.rst
Labels: cla-signed

#672 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#683 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#688 Update RNTemplate.rst
  doc/RNTemplate.rst
Labels: TEST, cla-signed

#693 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#692 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#695 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#697 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#698 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#699 Add knekrasov to CONTRIBUTORS
  CONTRIBUTORS.md
Labels: cla-signed

#701 Added office hours to the support.md page
  SUPPORT.md
  doc/meetings/CORTX Community Office Hours with Justin Woo.ics
  doc/meetings/CORTX Community Office Hours with Patrick Hession.ics
Labels: cla-signed

#700 Add myself to the CONTRIBUTORS.md.
  CONTRIBUTORS.md
Labels: cla-signed

#702 Update SUPPORT.md
  SUPPORT.md
Labels: cla-signed

#710 Get total user count from slack
  metrics/slack.py
  metrics/slack/slack.encrypted
  metrics/slack/slack.key
  metrics/slack/slack_user_count.py
Labels: cla-signed

#713 MTA Feb pdf
  doc/meetings/PDFs/Building the Ultimate Object Store.pdf
Labels: cla-signed

#714 Update README.rst adding links
  doc/meetings/README.rst
Labels: cla-signed

#719 Added myself to contributors list
  CONTRIBUTORS.md
Labels: cla-signed

#716 Update CONTRIBUTORS
  CONTRIBUTORS.md
Labels: cla-signed

#729 Added the name in contributors list
  CONTRIBUTORS.md
Labels: cla-signed

#726 Added my name in contributor list.
  CONTRIBUTORS.md
Labels: cla-signed

#730 Add Name In Contributors List
  CONTRIBUTORS.md
Labels: cla-signed

#731 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#735 Update contributors list
  CONTRIBUTORS.md
Labels: cla-signed

#725 Update list of contributors to `cortx-manager`
  CONTRIBUTORS.md
Labels: cla-signed

#737 Added My name in the S3 Contributors list
  CONTRIBUTORS.md
Labels: cla-signed

#741 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#736 Update CONTRIBUTORS.md (Evgeniy Brazhnikov)
  CONTRIBUTORS.md
Labels: cla-signed

#748 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#717 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#718 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#722 Adding my name to contributors list
  CONTRIBUTORS.md
Labels: cla-signed

#723 Adding myself to contributors list
  CONTRIBUTORS.md
Labels: cla-signed

#727 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#732 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#734 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#742 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#744 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#745 Update contributors.md file
  CONTRIBUTORS.md
Labels: cla-signed

#746 Added myself to the list of contributors.
  CONTRIBUTORS.md
Labels: cla-signed

#747 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#750 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#751 Added Shipra Gupta to the contributor's list.
  CONTRIBUTORS.md
Labels: cla-signed

#753 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#754 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#755 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#756 updated CONTRIBUTORS.md file
  CONTRIBUTORS.md
Labels: cla-signed

#757 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#758 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#760 Update README.rst
  doc/meetings/README.rst
Labels: cla-signed

#762 Added name to contributors
  CONTRIBUTORS.md
Labels: cla-signed

#752 Update the list of contributors (Ivan A.)
  CONTRIBUTORS.md
Labels: cla-signed

#761 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#728 Add name CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: cla-signed

#781 Formatted Document based on ticket
  doc/GitHub_Processes_and_Tools.rst
Labels: cla-signed

#784 Slack user count extraction scheduler
  .github/workflows/slack.yml
  metrics/slack/slack.encrypted.foo
  metrics/slack/slack.key
  metrics/slack/slack_user_count.py
Labels: cla-signed

#791 Improved steps to compile CORTX build using docker image
  doc/Release_Build_Creation.rst
Labels: cla-signed

#792 Update .whitesource
  .whitesource
Labels: cla-signed

#793 Added Link to run Motr on a cluster
  QUICK_START.md
Labels: cla-signed

#798 Updated link to motr in a cluster guide
  QUICK_START.md
Labels: cla-signed

#789 AWS ec2 integration
  QUICK_START.md
  doc/integrations/AWS_EC2.md
  doc/integrations/AWS_EC2/EC2instanceType.png
  doc/integrations/AWS_EC2/EC2instanceWindowsServer2019.png
  doc/integrations/AWS_EC2/SelectAMI.png
  doc/integrations/AWS_EC2/WindowsSubnet.png
  doc/integrations/AWS_EC2/launchInstance.png
  doc/integrations/AWS_EC2/rebootInstance.png
  doc/integrations/AWS_EC2/securityGroups.png
  doc/integrations/AWS_EC2/t2microInstance.png
  doc/integrations/README.rst
Labels: cla-signed
