Repository Seagate/cortx, pull requests merged in 2022-04, with the labels that each got.

#1479 Update README.rst
  doc/meetings/README.rst
Labels: cla-signed

#1478 Update mma_invite.ics
  doc/meetings/mma_invite.ics
Labels: cla-signed

#1473 Update integrations parent page to add link to cortx-docker.
  doc/integrations/README.rst
Labels: cla-signed, needs-attention

#1472 issue-1407: Verified this document works for Virtual Box
  doc/ova/2.0.0/PI-5/CORTX_on_Open_Virtual_Appliance_PI-5.rst
Labels: SODACODE2022, SODAMED

#1489 CORTX-30701 Community Build steps improvements.
  doc/community-build/docker/cortx-all/README.md
Labels: cla-signed

#1490 CORTX-30691 - Community Build instructions improvements
  doc/community-build/docker/cortx-all/README.md
Labels: documentation, cla-signed

#1476 CORTX-29502: PI-6 OVA Instructions and Release Notes
  doc/ova/2.0.0/PI-6/CHANGELOG.md
  doc/ova/2.0.0/PI-6/CORTX_on_Open_Virtual_Appliance_PI-6.rst
  doc/ova/2.0.0/PI-6/S3_IO_Operations.md
Labels: cla-signed

#1494 CORTX-31029: Port number added in curl command to validate CSM API
  doc/ova/2.0.0/PI-6/CORTX_on_Open_Virtual_Appliance_PI-6.rst
Labels: cla-signed

#1496 OVA: Minor changes to validate CSM endpoint
  doc/ova/2.0.0/PI-6/CORTX_on_Open_Virtual_Appliance_PI-6.rst
Labels: cla-signed

#1498 Test OVA PI-6 setup and S3 IO.
  doc/ova/2.0.0/PI-6/CORTX_on_Open_Virtual_Appliance_PI-6.rst
Labels: cla-signed
