Repository Seagate/cortx, pull requests merged in 2022-11, with the labels that each got.

#1610 [Codacy Cleanup] Add a 'shell' directive
  doc/integrations/edgehealth/edgehealth-chatbot/bash.sh
Labels: cla-signed, codacy

#1659 Update CORTX_on_Open_Virtual_Appliance_PI-8.rst
  doc/ova/2.0.0/PI-8/CORTX_on_Open_Virtual_Appliance_PI-8.rst
Labels: cla-signed, needs-attention

#1651 Removed unnecessary files
  STM32-CORTX Integration.docx
  STM32-CORTX Integration.pdf
Labels: needs-attention

#1660 Update QUICK_START.md
  QUICK_START.md
Labels: cla-signed, needs-attention

#1662 Update README.md
  README.md
Labels: cla-signed

#1663 Update SUPPORT.md
  SUPPORT.md
Labels: cla-signed

#1664 Update FAQs.md
  FAQs.md
Labels: cla-signed
