Repository Seagate/cortx, pull requests merged in 2022-09, with the labels that each got.

#1642 Remove duplicate code of community build
  doc/community-build/cloud/AWS/.gitignore
  doc/community-build/cloud/AWS/README.md
  doc/community-build/cloud/AWS/setup.sh
  doc/community-build/cloud/AWS/single-node.tf
  doc/community-build/cloud/AWS/tool_setup.sh
  doc/community-build/cloud/AWS/user.tfvars
  doc/community-build/cloud/AWS/variable.tf
Labels: cla-signed

#1639 Fix Codacy "Quote this to prevent word splitting"
  doc/community-build/docker/cortx-all/Dockerfile
Labels: cla-signed

#1644 CORTX-32948: OVA Release Instructions
  doc/ova/2.0.0/PI-8/CORTX_on_Open_Virtual_Appliance_PI-8.rst
  doc/ova/2.0.0/PI-8/S3_IO_Operations.md
Labels: cla-signed

#1647 CORTX-32948: Update OVA Publish Image for latest Release
  doc/ova/2.0.0/PI-8/CORTX_on_Open_Virtual_Appliance_PI-8.rst
Labels: cla-signed, ova

#1641 Remove unused variable
  doc/community-build/docker/cortx-all/build.sh
Labels: cla-signed, needs-attention

#1632 Update github-process-readme.md
  doc/github-process-readme.md
Labels: cla-signed, needs-attention

#1649 Update GLOSSARY.md
  GLOSSARY.md
Labels: cla-signed

#1652 Update GLOSSARY.md
  GLOSSARY.md
Labels: cla-signed

#1654 CORTX-32948: CHANGELOG.md for OVA Release [v0.12.0]
  doc/ova/2.0.0/PI-8/CHANGELOG.md
Labels: cla-signed
